default: 

capture.exe: capture.c
	gcc -I C:/WpdPack/Include capture.c -o capture -L C:/Win10pcap/x64 -lwpcap -lws2_32
 
sendpack.exe: sendpack.c
	gcc -I C:/WpdPack/Include sendpack.c -o sendpack -L C:/Win10pcap/x64 -lwpcap -lws2_32
	#gcc -I C:/WpdPack/Include sendpack.c -o sendpack -L C:/wpdPack/Lib/x64 -lwpcap -lws2_32
 
